// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Infrastructure.Data;

namespace Product.Infrastructure.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220104133738_CreateDateBaseProduct")]
    partial class CreateDateBaseProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Product.Core.Entities.MarketEntity", b =>
                {
                    b.Property<int>("MarketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketName")
                        .HasColumnType("TEXT");

                    b.HasKey("MarketID");

                    b.ToTable("MarketEntities");
                });

            modelBuilder.Entity("Product.Core.Entities.PriceEntity", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PriceID");

                    b.ToTable("PraceEntities");
                });

            modelBuilder.Entity("Product.Core.Entities.ProductEntity", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("CopmanyEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
